---

# Enable /etc/services.d/ support?
etc_services: True

# Name of diverted /etc/services, do not change if diversion is active!
etc_services_diversion: '/etc/services.d/10_debian_etc_services'


# ---- Local services ----

# These lists allow you to generate entries for local services not included in
# officially distributed /etc/services file. They will generate separate files
# for each configured service in /etc/services.d/ which then will be assembled
# into complete /etc/services file.

# List of known parameters:
#  - name: ''                      name of the service, required
#  - port: ''                      port on which service is accessed, required
#  - protocols: [ 'tcp','udp' ]    list of protocols to generate, optional
#  - protocol: ''                  legacy protocol name to use, deprecated
#  - comment: ''                   comment to add to the service entry, optional
#  - filename: ''                  use this filename instead of a generated one
#  - custom: ''                    specify custom file contents instead of templated

# These lists should be used in inventory
etc_services_list: []
etc_services_group_list: []
etc_services_host_list: []

# This list can be used in a dependency variables for 'etc_services' role
etc_services_dependency_list: []       # deprecated
etc_services_dependent_list: []

  # Example entry
  #- name: 'servicename'
  #  port: '12345'
  #  protocols: [ 'tcp', 'udp' ]
  #  porotol: 'tcp'                    # deprecated
  #  comment: 'Example service'

