---
- name: create buildbot master
  sudo_user: "{{ buildbot_user }}"
  shell: chdir={{ buildbot_home }} buildbot create-master master

- name: buildbot master configuration
  sudo_user: "{{ buildbot_user }}"
  template:
    src: master.cfg.js
    dest: "{{ buildbot_home }}/master/master.cfg"
  when: buildbot_generate_master_cfg

- name: buildbot slave configuration
  sudo_user: "{{ buildbot_user }}"
  shell: chdir={{ buildbot_home }}/slaves/{{ item.name }} buildslave create-slave . {{ buildbot_web_host }}:{{ buildbot_slave_port }} {{ item.name }} {{ item.password }}
  with_items: "{{ buildbot_slaves }}"

- name: set slave admin information
  sudo_user: "{{ buildbot_user }}"
  copy:
    content: "{{ item.info.admin }}"
    dest: "{{ buildbot_home }}/slaves/{{ item.name }}/info/admin"
  with_items: "{{ buildbot_slaves }}"
  when: "item.info is defined and item.info.admin is defined"

- name: set slave host information
  sudo_user: "{{ buildbot_user }}"
  copy:
    content: "{{ item.info.host }}"
    dest: "{{ buildbot_home }}/slaves/{{ item.name }}/info/host"
  with_items: "{{ buildbot_slaves }}"
  when: "item.info is defined and item.info.host is defined"
