#!/usr/bin/env ruby
#^syntax detection

site "https://galaxy.ansible.com/api/v1"

role "bennojoy.network_interface"
role "maxb.smokeping", git:"https://github.com/max-b/ansible-smokeping.git", ref:"maxb"  
role "maxb.collectd", git:"https://github.com/max-b/ansible-collectd.git", ref:"maxb"
role "icinga.icinga2-ansible-no-ui", git:"https://github.com/max-b/icinga2-ansible.git", path: "icinga2-ansible-no-ui", ref:"maxb"
role "icinga.icinga2-ansible-classic-ui", git:"https://github.com/Icinga/icinga2-ansible.git", path: "icinga2-ansible-classic-ui"
role "icinga.icinga2-ansible-web-ui", git:"https://github.com/max-b/icinga2-ansible.git", path: "icinga2-ansible-web-ui", ref:"maxb"
role "icinga.icinga2-ansible-add-hosts", git:"https://github.com/Icinga/icinga2-ansible.git", path: "icinga2-ansible-add-hosts"
role "debops.snmpd"
role "debops.ferm"
role "debops.secret"
role "debops.apt_preferences"
role "debops.tcpwrappers"

