---

- name: Create or update archive of ~/.gnupg directory
  shell: tar uvpf gnupg.tar .gnupg && tar dpf gnupg.tar .gnupg || (
         tar cvpf gnupg.tar .gnupg) ; chmod 0600 ~/gnupg.tar chdir=~
  args:
    warn: False
  become_user: '{{ reprepro_user }}'
  changed_when: False

- name: Upload ~/.gnupg archive to Ansible Controller
  fetch:
    src: '{{ reprepro_home + "/gnupg.tar" }}'
    dest: '{{ secret + "/reprepro/" + ansible_domain + "/snapshots/" + ansible_fqdn + "/" + reprepro_distribution | lower + "/gnupg.tar" }}'
    flat: True

