---

dependencies:
  - role: debops.secret
  - role: debops.etc_services
  - role: debops.ferm

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Install and manage PostgreSQL database clusters'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - 'database:sql'
  - 'system'

