---

- name: Add PGDG APT key
  apt_key: url={{ postgresql_pgdg_key_url }} id={{ postgresql_pgdg_key_id }}
           state=present

- name: Add PGDG APT repository
  apt_repository: repo='deb {{ postgresql_pgdg_repository }} {{ postgresql_pgdg_distribution }} main'
                  state=present update_cache=yes

- name: Install PGDG keyring
  apt: pkg=pgdg-keyring state=latest install_recommends=no


