---

- name: Check if PostgreSQL is installed
  stat: path=/usr/lib/postgresql/{{ postgresql_version }}/bin/postmaster
  register: postgresql_install_postmaster

- name: Install PostgreSQL packages
  apt: pkg={{ item }} state=present install_recommends=no
  with_flattened:
    - [ 'python-psycopg2', 'postgresql-{{ postgresql_version }}', 'postgresql-client-{{ postgresql_version }}' ]
    - postgresql_packages

- name: Check if default PostgreSQL cluster exists
  stat: path=/var/lib/postgresql/{{ postgresql_version }}/main/postmaster.opts
  register: postgresql_install_main

  # Main cluster will be recreated later, with correct encoding
- name: Remove default PostgreSQL cluster on first install
  command: pg_dropcluster --stop {{ postgresql_version }} main
  when: postgresql_install_postmaster is defined and postgresql_install_postmaster.stat.exists == False and
        postgresql_install_main is defined and postgresql_install_main.stat.exists == True

