---

- name: Install autopostgresqlbackup
  apt: pkg=autopostgresqlbackup state=present install_recommends=no

- name: Divert the original autopostgresqlbackup script
  command: dpkg-divert --quiet --local --divert /usr/share/doc/autopostgresqlbackup/script.dpkg-divert --rename /usr/sbin/autopostgresqlbackup creates=/usr/share/doc/autopostgresqlbackup/script.dpkg-divert

- name: Divert the original autopostgresqlbackup cron
  command: dpkg-divert --quiet --local --divert /usr/share/doc/autopostgresqlbackup/cron.dpkg-divert --rename /etc/cron.daily/autopostgresqlbackup creates=/usr/share/doc/autopostgresqlbackup/cron.dpkg-divert

- name: Configure autopostgresqlbackup defaults
  template: src=etc/default/autopostgresqlbackup.j2
            dest=/etc/default/autopostgresqlbackup
            owner=root group=root mode=0644

- name: Configure autopostgresqlbackup
  template: src=usr/sbin/autopostgresqlbackup.j2
            dest=/usr/sbin/autopostgresqlbackup-{{ item.version | default(postgresql_version) }}-{{ item.name }}
            owner=root group=root mode=0755
  with_flattened:
    - postgresql_default_cluster
    - postgresql_clusters

- name: Disable autopostgresqlbackup from running daily
  file: path=/etc/cron.daily/autopostgresqlbackup-{{ item.version | default(postgresql_version) }}-{{ item.name }}
        state=absent
  when: not postgresql_auto_backup
  with_flattened:
    - postgresql_default_cluster
    - postgresql_clusters

- name: Enable autopostgresqlbackup to run daily
  template: src=etc/cron.daily/autopostgresqlbackup.j2
        dest=/etc/cron.daily/autopostgresqlbackup-{{ item.version | default(postgresql_version) }}-{{ item.name }}
        owner=root group=root mode=0755
  when: postgresql_auto_backup
  with_flattened:
    - postgresql_default_cluster
    - postgresql_clusters
