---
- name: Add wheezy to sources.list
  apt_repository: repo='{{item}}' state=present
  with_items:
    - deb-src http://http.debian.net/debian wheezy main
    - deb http://http.debian.net/debian wheezy main

- name: Install build tools
  apt: pkg={{ item  }} state=present force=yes
  with_items:
    - build-essential
    - libnl-dev

- name: Remove wheezy from sources.list
  apt_repository: repo='{{item}}' state=absent
  with_items:
    - deb-src http://http.debian.net/debian wheezy main
    - deb http://http.debian.net/debian wheezy main

- name: Clone tunneldigger repo
  git: repo=https://github.com/sudomesh/tunneldigger.git
       force=yes
       dest=/opt/tunneldigger

- name: Compile tunneldigger
  command: creates=/opt/tunneldigger/client/l2tp_client chdir=/opt/tunneldigger/client make l2tp_client

- name: Init required kernel modules
  command: "modprobe {{ item }}"
  with_items:
    - nf_conntrack_netlink 
    - nf_conntrack 
    - nfnetlink 
    - l2tp_netlink 
    - l2tp_core 
    - l2tp_eth
  tags: modprobe

- name: Create systemd service file
  template: dest=/lib/systemd/system/tunneldigger-client.service
            src=tunneldigger-client.service.j2
            force=yes
            mode=0644
  tags: create-systemd

- name: Ensure that hook path exists
  file: path={{ up_hook_script_path }} state=directory
  tags: create-hook

- name: Create hook file
  template: dest={{ up_hook_script_path }}/{{ up_hook_script_name }}
            src=tunnel-up-hook.sh.j2
            force=yes
            mode=0755
  tags: create-hook

- name: Create defaults file
  template: dest=/etc/default/tunneldigger-client 
            src=tunneldigger-client.defaults.j2
            force=yes
            mode=0644
  tags: create-defaults
  notify:
    - restart tunneldigger service
