---
galaxy_info:
  author: Emilien Mantel
  description: Simple firewall for Debian/Ubuntu (with UFW/fail2ban)
  company:
  license: GPLv2
  min_ansible_version: 1.6
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - networking
  - system
dependencies: []

