---

- name: Ensure owncloud packages are installed
  apt:
    name: owncloud
    state: present
    install_recommends: False
  tags: owncloud

- include: configure_mysql.yml
  when: owncloud_database == 'mysql'
  tags: [ 'owncloud', 'mysql' ]

- include: configure_postgresql.yml
  when: owncloud_database == 'postgresql'
  tags: [ 'owncloud', 'postgresql' ]

- include: configure_owncloud.yml
  tags: owncloud

