---

- name: Check if default configuration is static
  command: grep -q 'static' /etc/network/interfaces
  register: ifupdown_register_static_config
  changed_when: False
  failed_when: False

- name: Enable static default configuration if detected
  set_fact:
    ifupdown_static_config: 'static'
  when: ifupdown_register_static_config.rc == 0

