---
# Default variables
# =================

# .. contents:: Sections
#    :local:

# .. envvar:: apt_preferences_list
#
# List of apt_preferences(5) pins to configure in ``/etc/apt/preferences.d/``.
# These pins will be configured on all hosts in the cluster, if set in
# ``inventory/group_vars/all/``. See :ref:`apt_preferences_list` for more
# details.
apt_preferences_list: []


# .. envvar:: apt_preferences_group_list
#
# List of apt_preferences(5) pins to configure in ``/etc/apt/preferences.d/``.
# These pins will be configured on hosts in a specified group, if set in
# ``inventory/group_vars/group_name/``. Only one group "level" is supported.
apt_preferences_group_list: []


# .. envvar:: apt_preferences_host_list
#
# List of apt_preferences(5) pins to configure in ``/etc/apt/preferences.d/``.
# These pins will be configured on specific hosts, if set in
# ``inventory/host_vars/host_name/``.
apt_preferences_host_list: []


# .. envvar:: apt_preferences_dependent_list
#
# List of apt_preferences(5) pins to configure in ``/etc/apt/preferences.d/``.
# This variable is meant to be used from a role dependency in
# ``role/meta/main.yml`` or in a playbook.
apt_preferences_dependent_list: []


# .. envvar:: apt_preferences_priority_default
#
# Default pin priority used, if custom priority is not specified in a pin
# definition.
apt_preferences_priority_default: '500'


# .. envvar:: apt_preferences_priority_version
#
# Default pin priority used if custom priority is not specified in a versioned
# pin definition.
apt_preferences_priority_version: '1001'


# .. envvar:: apt_preferences_next_release
#
# Hash of future releases of current stable distributions. This is used to
# check if role can create autogenerated pin with preference for backported
# packages from ``<release>-backports`` repository.
apt_preferences_next_release:

  # Debian releases
  'lenny':    'squeeze'
  'squeeze':  'wheezy'
  'wheezy':   'jessie'
  'jessie':   'stretch'

  # Ubuntu releases
  'precise':  'quantal'
  'quantal':  'raring'
  'raring':   'saucy'
  'saucy':    'trusty'
  'trusty':   'utopic'

