---

# Debian previous releases
reprepro_debian_previous:
  'wheezy': 'squeeze'
  'jessie': 'wheezy'
  'stretch': 'jessie'

# Debian next releases
reprepro_debian_next:
  'wheezy': 'jessie'
  'jessie': 'stretch'

# Debian releases by suite
reprepro_debian_releases:
  'oldoldstable': 'squeeze'
  'oldstable': 'wheezy'
  'stable': 'jessie'
  'testing': 'stretch'

# Debian suites by release
reprepro_debian_suites:
  'squeeze': 'oldoldstable'
  'wheezy': 'oldstable'
  'jessie': 'stable'
  'stretch': 'testing'

# List of Debian architectures by release
reprepro_debian_architectures:
  'squeeze': [ 'source', 'amd64', 'armel', 'i386' ]
  'wheezy': [ 'source', 'amd64', 'armel', 'armhf', 'i386' ]
  'jessie': [ 'source', 'amd64', 'arm64', 'armel', 'armhf', 'i386' ]
  'stretch': [ 'source', 'amd64', 'arm64', 'armel', 'armhf', 'i386' ]

# Configuration for HTTP server
reprepro_nginx_server_http:
  by_role: 'debops.reprepro'
  enabled: True
  ssl: False
  redirect_to_ssl: '{{ reprepro_nginx_access_policy }}'
  filename: '{{ reprepro_domains[0] + "_http" }}'
  name: '{{ reprepro_domains }}'
  root: '{{ reprepro_repository_path }}'

  location:
    '/': |
      try_files $uri $uri/ =404;
      autoindex on;
      autoindex_exact_size off;
      autoindex_localtime on;

  location_allow:
    '/': '{{ reprepro_allow }}'


# Configuration for HTTPS server
reprepro_nginx_server_https:
  by_role: 'debops.reprepro'
  enabled: True
  listen: False
  filename: '{{ reprepro_domains[0] + "_https" }}'
  name: '{{ reprepro_domains }}'
  root: '{{ reprepro_repository_path }}'

  access_policy: '{{ reprepro_nginx_access_policy }}'
  auth_basic_realm: '{{ reprepro_nginx_auth_realm }}'

  options: |
    client_max_body_size {{ reprepro_max_body_size }}M;

  location:
    '/': |
      try_files $uri $uri/ =404;
      autoindex on;
      autoindex_exact_size off;
      autoindex_localtime on;

    '/upload': |
      alias {{ reprepro_upload }};
      dav_access all:rw;
      dav_methods PUT;
      limit_except PUT {
              deny all;
      }

  location_allow:
    '/': '{{ reprepro_allow }}'
    '/upload': '{{ reprepro_allow_upload }}'

