---

dependencies:

  - role: debops.secret

  - role: debops.etc_services

  - role: debops.nodejs

  - role: debops.mysql
    when: (etherpad_dependencies is defined and etherpad_dependencies) and
          (etherpad_database is defined and etherpad_database and etherpad_database == 'mysql')

    mysql_databases:
      - name: '{{ etherpad_database_config[etherpad_database].database }}'
        state: 'present'

    mysql_users:
      - name: '{{ etherpad_database_config[etherpad_database].username }}'
        host: '{{ etherpad_database_config[etherpad_database].hostname }}'
        priv: '{{ etherpad_database_config[etherpad_database].database }}.*:ALL'
        state: 'present'

  - role: debops.nginx
    nginx_servers: [ '{{ etherpad_nginx_server }}' ]
    nginx_upstreams: [ '{{ etherpad_nginx_upstream }}' ]
    when: (etherpad_dependencies is defined and etherpad_dependencies)
    tags: nginx

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Install and manage Etherpad Lite'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - system
  - web

