---

dependencies:

  - role: debops.secret
    tags: [ 'depend::secret', 'depend::secret:apt',
            'depend-of::apt', 'type::dependency:hard' ]

  - role: debops.apt_preferences
    tags: [ 'depend::apt_preferences', 'depend::apt_preferences:apt',
            'depend-of::apt', 'type::dependency:hard' ]
    apt_preferences_dependent_list:

      - package: 'git git-*'
        backports: [ 'wheezy' ]
        reason:  'Better support for git submodules - http://stackoverflow.com/a/7593496'
        by_role: 'debops.apt'

      - package: 'irqbalance'
        backports: [ 'wheezy' ]
        reason:  'Issues in wheezy package - http://debian.distrosfaqs.org/debian-user/wheezy-irqbalance/'
        by_role: 'debops.apt'

      - package: 'apt-cacher-ng'
        backports: [ 'jessie' ]
        reason:  'http://httpredir.debian.org/debian is not included in the deb_mirrors.gz file of apt-cacher-ng as of 0.8.0-3 (latest in Debian Jessie). This can results in unnecessary resource (bandwidth, storage) usage.'
        by_role: 'debops.apt'


  #- role: debops.etc_services
  #  when: (apt is defined and apt) and (apt != True and apt == ansible_fqdn)

  #- role: debops.ferm
  #  when: (apt is defined and apt) and (apt != True and apt == ansible_fqdn)


galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Configure and manage APT Package Manager'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - system

