---

- name: APT | Install fail2ban
  apt: pkg=fail2ban state=latest

#- name: INI | Configure fail2ban
#  ini: section=Definition

- name: Template | Configure fail2ban jail
  template: src=etc/fail2ban/jail.local.j2 dest=/etc/fail2ban/jail.local
  notify: restart fail2ban

- name: TEMPLATE | Deploy UFW integration on Fail2ban on Wheezy
  template: src=etc/fail2ban/action.d/ufw.conf.j2 dest=/etc/fail2ban/action.d/ufw.conf
  notify: restart fail2ban
  when: "{{ ansible_distribution_major_version | version_compare('8.0', 'lt') }}"
