---

- name: APT | Install ufw
  apt: pkg=ufw update_cache=yes cache_valid_time=3600

- name: UFW | Reset firewall
  ufw: state=reset
  when: firewall_reset

- name: INCLUDE | Config
  include: config.yml

- name: INCLUDE | Firewall
  include: firewall.yml

- name: INCLUDE | Fail2ban
  include: fail2ban.yml
  when: firewall_use_fail2ban
