---

- name: Install apt-cacher-ng on cache server
  apt: pkg=apt-cacher-ng state=latest install_recommends=no

- name: Configure apt-cacher-ng on cache server
  template: src={{ item }}.j2 dest=/{{ item }} owner=root group=root mode=0644
  with_items:
    - 'etc/apt-cacher-ng/acng.conf'
    - 'etc/apt-cacher-ng/security.conf'
  notify:
    - Restart apt-cacher-ng

- name: Configure apt-cacher-ng port in /etc/services
  template: src=etc/services.d/50_acng.j2
            dest=/etc/services.d/acng.j2
            owner=root group=root mode=0644
  notify:
    - Assemble services.d

- name: Allow access to apt-cacher-ng through firewall
  template: src=etc/ferm/filter-input.d/apt-cacher-ng.conf.j2
            dest=/etc/ferm/filter-input.d/apt-cacher-ng.conf
            owner=root group=adm mode=0644
  notify:
    - Restart ferm

- name: Flush handlers if needed for apt-cacher-ng
  meta: flush_handlers


