---

- name: Enable Linux firmware packages on hosts that require it
  set_fact:
    apt_conditional_firmware: '{{ apt_conditional_firmware_packages[ansible_distribution] }}'
  when: ('firmware' in apt_conditional_whitelist and
         ansible_system == 'Linux' and ansible_form_factor in ['Rack Mount Chassis'])

- name: Enable irqbalance on multi-core systems
  set_fact:
    apt_conditional_irqbalance: [ 'irqbalance' ]
  when: ('irqbalance' in apt_conditional_whitelist and ansible_processor_cores >= 2 and
         (ansible_virtualization_role is undefined or ansible_virtualization_role not in [ 'guest' ]))

- name: Enable uptimed on hardware systems
  set_fact:
    apt_conditional_uptimed: [ 'uptimed' ]
  when: ('uptimed' in apt_conditional_whitelist and
         (ansible_virtualization_role is undefined or ansible_virtualization_role not in [ 'guest' ]))

- name: Gather conditional packages in one list
  set_fact:
    apt_conditional_packages: '{{ apt_conditional_firmware     | default([]) +
                                  apt_conditional_irqbalance   | default([]) +
                                  apt_conditional_uptimed      | default([]) }}'

- name: Install requested packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_flattened:
    - '{{ apt_base_packages }}'
    - '{{ apt_packages }}'
    - '{{ apt_group_packages }}'
    - '{{ apt_host_packages }}'
    - '{{ apt_conditional_packages }}'

