---

- name: Install apticron and apt-listchanges
  apt:
    pkg: '{{ item }}'
    state: 'latest'
    install_recommends: no
  with_items: [ 'apt-listchanges', 'apticron' ]
  when: apt_update_notifications

- name: Configure apticron and apt-listchanges
  template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: 0644
  with_items: [ 'etc/apt/listchanges.conf', 'etc/apticron/apticron.conf' ]
  when: apt_update_notifications

- name: Remove apticron and apt-listchanges
  apt:
    pkg: '{{ item }}'
    state: 'absent'
    purge: yes
  with_items: [ 'apt-listchanges', 'apticron' ]
  when: not apt_update_notifications



