---

- name: Reload sysctl
  command: sysctl --system

- name: Restart ferm
  service:
    name: 'ferm'
    state: 'restarted'
  when: (ferm_enabled | bool and (ansible_local|d() and
         (ansible_local.root|d() and (ansible_local.root.flags | intersect(ferm_root_flags.cap_net_admin)) or
         (ansible_local.cap12s|d() and (not ansible_local.cap12s.enabled | bool or
         (ansible_local.cap12s.enabled | bool and 'cap_net_admin' in ansible_local.cap12s.list))))))

