---

# Can not changed directly. To change it define apt_default_sources in your
# inventory variables (same as below).
# Then you can change the apt_default_sources_sections directly.
apt_default_sources_sections:
  - 'main'
  - 'contrib'
  - 'non-free'
  - 'rpi'

# List of default repositories for Raspbian GNU/Linux
apt_default_sources:
  - comment:  'Raspbian Main Repository'
    mirrors:  [ 'http://mirrordirector.raspbian.org/raspbian/' ]
    releases: [ '{{ apt_sources_release }}' ]
    sections: '{{ apt_default_sources_sections }}'
